apiVersion: v1
kind: Pod
metadata:
  name: init-demo
  labels:
    name: myapp
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          memory: '128Mi'
          cpu: '200m'
      ports:
        - containerPort: 80
      volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
  initContainers:
    - name: install
      image: busybox
      command:
        - wget
        - '-O'
        - '/work-dir/index.html'
        - http://info.cern.ch
      volumeMounts:
        - name: workdir
          mountPath: '/work-dir'
  volumes:
    - name: workdir
      emptyDir: {}
